config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :billings
  resources :physicians
  resources :physicians
  resources :physicians
  resources :physicians
  resources :vitals
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/home'

  get 'welcome/dashboard'

  get 'welcome/reports'

  get 'welcome/billing' 

  get 'welcome/vitals'

  resources :vitals
  root to: 'welcome#home'
  

end

app/models/vital.rb
class Vital < ActiveRecord::Base
  belongs_to :physician
end

app/controllers/vitals_controller.rb
class VitalsController < ApplicationController
  before_action :set_vital, only: [:show, :edit, :update, :destroy]

  # GET /vitals
  # GET /vitals.json
  def index
    @search = VitalSearch.new(params[:search])
    @vitals = @search.scope
  end

  # GET /vitals/1
  # GET /vitals/1.json
  def show
  end

  # GET /vitals/new
  def new
    @vital = Vital.new
  end

  # GET /vitals/1/edit
  def edit
  end

  # POST /vitals
  # POST /vitals.json
  def create
    @vital = Vital.new(vital_params)

    respond_to do |format|
      if @vital.save
        format.html { redirect_to @vital, notice: 'Vital was successfully created.' }
        format.json { render :show, status: :created, location: @vital }
      else
        format.html { render :new }
        format.json { render json: @vital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vitals/1
  # PATCH/PUT /vitals/1.json
  def update
    respond_to do |format|
      if @vital.update(vital_params)
        format.html { redirect_to @vital, notice: 'Vital was successfully updated.' }
        format.json { render :show, status: :ok, location: @vital }
      else
        format.html { render :edit }
        format.json { render json: @vital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vitals/1
  # DELETE /vitals/1.json
  def destroy
    @vital.destroy
    respond_to do |format|
      format.html { redirect_to vitals_url, notice: 'Vital was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vital
      @vital = Vital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vital_params
      params.require(:vital).permit(:date, :Patient_ID, :vital_type, :Vital_Value, :physician_id)
    end
end

app/helpers/vitals_helper.rb
module VitalsHelper
end

app/views/vitals/_form.html.erb
<div class = "row">
      <%= form_for @vital, html:{class: 'form-horizontal'} do |f| %>
        <% if @vital.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@vital.errors.count, "error") %> prohibited this vital from being saved:</h2>

            <ul>
            <% @vital.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

<div class="control-group">
  <%= f.label :date,class:'control-label' %><br>
  <div class ="controls">
    <%= f.date_select :date %>  
  </div>
</div> 
  
<div class="control-group">
  <%= f.label :Patient_ID,class:'control-label' %><br>
  <div class ="controls">
    <%= f.text_field :Patient_ID %>
  </div>
</div>
  
<div class="control-group">
  <%= f.label :"Vital-Type",class:'control-label' %><br>
  <div class ="controls">
    <%= f.select(:vital_type,options_for_select([['Blood-Pressure','Blood-Pressure'],['Blood-Sugar','Blood-Sugar'],['Weight','Weight'],['Heartbeat','Heartbeat']]),{include_blank:true}) %>
  </div>
</div>
  
<div class="control-group">
  <%= f.label :Vital_Value,class:'control-label' %><br>
  <div class ="controls">
    <%= f.text_field :Vital_Value %>
  </div>
</div>
  
  <div class="control-group">
    <%= f.label :Doctor ,class:'control-label' %><br>
    <div class ="controls">
      <%= collection_select( :vital,  :physician_id,  Physician.all, :id, :name, {}, { :multiple => false } )%>
    </div>
</div>
  
 <div class="control-group">
   <div class ="controls">
     <%= f.submit 'Submit',class: 'btn btn-default' %>
   </div>
  </div>
<% end %>
</div>

app/views/vitals/edit.html.erb
<h1>Editing Vital</h1>

<%= render 'form' %>

<%= link_to 'Show', @vital %> |
<%= link_to 'Back', vitals_path %>

app/views/vitals/index.html.erb
<div class ="row">
  <h1>Upload Vitals</h1>
  <div class="pull-right range-query">
    <%= form_tag vitals_path, method: :get do %>
    <%= text_field_tag 'search[date_from]',@search.date_from %>
    <%= text_field_tag 'search[date_to]',@search.date_to %>
    <%= submit_tag 'Search',class: 'btn search-button' %>
    <% end %>
  </div>
</div>
<div class =  "media">
 <div class = "media-body">
 <table class="table table-hover">
          <thead>
            <tr>
              <th>Date</th>
              <th>Patient ID</th>
              <th>Vital Type</th>
              <th>Vital Value</th>
              <th>Physician Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @vitals.each do |vital| %>
              <tr>
                <td><%= vital.date %></td>
                <td><%= vital.Patient_ID %></td>
                <td><%= vital.vital_type %></td>
                <td><%= vital.Vital_Value %></td>
                <td><%= vital.physician.name %></td>
                <td><%= link_to 'Show', vital,class:'btn btn-mini' %></td>
                <td><%= link_to 'Edit', edit_vital_path(vital),class:'btn btn-mini btn-success' %></td>
                <td><%= link_to 'Delete', vital, method: :delete,class:'btn btn-mini btn-danger' ,data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

  </div>
  </div>
<br>

<%= link_to 'New Vital', new_vital_path %>

app/views/vitals/new.html.erb
<h1>New Vital</h1>

<%= render 'form' %>

<%= link_to 'Back', vitals_path %>

app/views/vitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @vital.date %>
</p>

<p>
  <strong>Patient ID:</strong>
  <%= @vital.Patient_ID %>
</p>

<p>
  <strong>Vital value:</strong>
  <%= @vital.Vital_Value %>
</p>

<%= link_to 'Edit', edit_vital_path(@vital) %> |
<%= link_to 'Back', vitals_path %>