config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :billings
  resources :physicians
  resources :physicians
  resources :physicians
  resources :physicians
  resources :vitals
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/home'

  get 'welcome/dashboard'

  get 'welcome/reports'

  get 'welcome/billing' 

  get 'welcome/vitals'

  resources :vitals
  root to: 'welcome#home'
  

end

app/models/billing.rb
class Billing < ActiveRecord::Base
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
  before_action :set_billing, only: [:show, :edit, :update, :destroy]

  # GET /billings
  # GET /billings.json
  def index
    @billings = Billing.all
  end

  # GET /billings/1
  # GET /billings/1.json
  def show
  end

  # GET /billings/new
  def new
    @billing = Billing.new
  end

  # GET /billings/1/edit
  def edit
  end

  # POST /billings
  # POST /billings.json
  def create
    @billing = Billing.new(billing_params)

    respond_to do |format|
      if @billing.save
        format.html { redirect_to @billing, notice: 'Billing was successfully created.' }
        format.json { render :show, status: :created, location: @billing }
      else
        format.html { render :new }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /billings/1
  # PATCH/PUT /billings/1.json
  def update
    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to @billing, notice: 'Billing was successfully updated.' }
        format.json { render :show, status: :ok, location: @billing }
      else
        format.html { render :edit }
        format.json { render json: @billing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /billings/1
  # DELETE /billings/1.json
  def destroy
    @billing.destroy
    respond_to do |format|
      format.html { redirect_to billings_url, notice: 'Billing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_billing
      @billing = Billing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def billing_params
      params.require(:billing).permit(:Date, :Reason, :Hospital, :Status)
    end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/_form.html.erb
<%= form_for(@billing) do |f| %>
  <% if @billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
      <% @billing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Date ,class:'control-label'%><br>
    <div class ="controls">
    <%= f.datetime_select :Date %>
  </div>
</div>

  <div class="control-group">
    <%= f.label :Reason ,class:'control-label'%><br>
    <div class ="controls">
    <%= f.text_field :Reason %>
  </div>
</div>

  <div class="control-group">
    <%= f.label :Hospital,class:'control-label' %><br>
    <div class ="controls">
    <%= f.text_field :Hospital %>
  </div>
</div>

  <div class="control-group">
    <%= f.label :Status ,class:'control-label'%><br>
    <div class ="controls">
    <%= f.select(:Status,options_for_select([['Paid','Paid'],['Pending','Pending']]),{include_blank:true}) %>
  </div>
</div>

 <div class="control-group">
   <div class ="controls">
     <%= f.submit 'Submit',class: 'btn btn-default' %>
   </div>
  </div>
<% end %>

app/views/billings/edit.html.erb
<h1>Editing Billing</h1>

<%= render 'form' %>

<%= link_to 'Show', @billing %> |
<%= link_to 'Back', billings_path %>

app/views/billings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bills</h1>
<div class =  "media">
 <div class = "media-body">
 <table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Reason</th>
      <th>Hospital</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billings.each do |billing| %>
      <tr>
        <td><%= billing.Date %></td>
        <td><%= billing.Reason %></td>
        <td><%= billing.Hospital %></td>
        <td><%= billing.Status %></td>
        <td><%= link_to 'Show', billing,class:'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_billing_path(billing),class:'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Delete', billing, method: :delete,class:'btn btn-mini btn-danger' ,data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
          </tbody>
        </table>

  </div>
  </div>
<br>

<%= link_to 'New Billing', new_billing_path %>

app/views/billings/new.html.erb
<h1>New Billing</h1>

<%= render 'form' %>

<%= link_to 'Back', billings_path %>

app/views/billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @billing.Date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @billing.Reason %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @billing.Hospital %>
</p>

<p>
  <strong>Status:</strong>
  <%= @billing.Status %>
</p>

<%= link_to 'Edit', edit_billing_path(@billing) %> |
<%= link_to 'Back', billings_path %>