config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :billings
  resources :physicians
  resources :physicians
  resources :physicians
  resources :physicians
  resources :vitals
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/home'

  get 'welcome/dashboard'

  get 'welcome/reports'

  get 'welcome/billing' 

  get 'welcome/vitals'

  resources :vitals
  root to: 'welcome#home'
  

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:Date, :Report)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :Date,class:'control-label' %><br>
    <div class ="controls">
    <%= f.date_select :Date %>
    </div>
</div>

  <div class="control-group">
    <%= f.label :Report ,class:'control-label'%><br>
    <div class ="controls">
    <%= f.text_field :Report %>
    </div>
</div>

 <div class="control-group">
   <div class ="controls">
     <%= f.submit 'Submit',class: 'btn btn-default' %>
   </div>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>


<div class =  "media">
 <div class = "media-body">
 <table class="table table-hover">
 <thead>
   <tr>
     <th>Date</th>
     <th>Report</th>
     <th colspan="3"></th>
   </tr>
   </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.Date %></td>
        <td><%= report.Report %></td>
        <td><%= link_to 'Show', report,class:'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_report_path(report),class:'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Delete', report,  method: :delete,class:'btn btn-mini btn-danger' ,data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
          </tbody>
        </table>
  </div>
</div>
<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @report.Date %>
</p>

<p>
  <strong>Report:</strong>
  <%= @report.Report %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>