config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :billings
  resources :physicians
  resources :physicians
  resources :physicians
  resources :physicians
  resources :vitals
  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'welcome/home'

  get 'welcome/dashboard'

  get 'welcome/reports'

  get 'welcome/billing' 

  get 'welcome/vitals'

  resources :vitals
  root to: 'welcome#home'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patientportal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <ul class="nav nav-tabs">
   <% if current_user %>
      <div class="container">
      <ul class="nav nav-tabs">
          <li> <%= link_to "Dashboard", welcome_dashboard_path %> </li>
          <li> <%= link_to "Reports", reports_path %> </li>
          <li> <%= link_to "Billing", billings_path %> </li>
          <li><%= link_to "Vitals",vitals_path %></li>
          <li> <%= link_to "Sign Out", destroy_user_session_path,method: :delete %> </li>
             <div class='btn-group pull-right right-nav'>
     <button type="button" class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Add Physician</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Physician",physicians_path %></li>
        </ul>
      </div>
      </ul>
      </div>

        <% else %>
        <li> <%= link_to "Home", root_path %> </li>
        <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <li> <%= link_to "Sign In", new_user_session_path %> </li>
    <% end %>
        </ul>
  
  <%if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
    </div>
    <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>   
  </div>
      <% elsif flash[:alert] %>
    <div class="alert alert-alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert ] %>  
  </div>
  <% end %>
  
<%= yield %>

</body>
</div>
</html>